### ISSUE TITLE
PriceList.__exit__ not correctly implemented

### ISSUE THREAD

**Issue by inftp** [ciasia/tancho#3]
The line "os.unlink(self.csv_path)" creates the below error

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 

Currently disabled as a workaround

**Comment by kimburgess** [comment]
It looks like you may be [opening up that file in `__init__`](https://github.com/ciasia/tancho/blob/master/pricelist.py#L41), but are not closing it. See what you can do to refactor slightly so you can ensure everything releases neatly.

**Comment by inftp** [comment]
Changed **csv_file** to be a property of PriceList and called **close()** function in **exit**

Error no longer appears. Marking as resolved.
